#!/bin/bash -exv

autowrap="./_autowrap"
$autowrap || (ipdb3 $autowrap && exit 1)

#autowrap_include=$(python -c 'import pkg_resources; print(pkg_resources.resource_filename("autowrap", "data_files"))')
#cython="cython --fast-fail --line-directives -p -I. -I$autowrap_include/autowrap -t -v --gdb --cplus"
#$cython hparser.pyx

python setup.py build_ext --inplace

ipython -i --pdb test.py
